cargo-features = ["edition2024"]

[package]
name = "multithread"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rayon = "1.11.0"
wasm-bindgen = "0.2.101"
wasm-bindgen-rayon = { version = "1.3.0", features = ["no-bundler"]}
