cargo-features = ["edition2024"]

[package]
name = "singlethread"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
getrandom = { version = "0.3.3", features = ["wasm_js"] }
rand = "0.9.2"
wasm-bindgen = "0.2.104"
