[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.compile-singlethread]
cwd = "D:/wasm-research/rust/singlethread"
command = "wasm-pack"
args = ["build", "--target", "web", "--out-dir", "../../public/singlewasm"]

[tasks.compile-multithread]
cwd = "D:/wasm-research/rust/multithread"
command = "wasm-pack"
args = ["build", "--target", "web", "--out-dir", "../../public/multiwasm"]

[tasks.compile-backend]
cwd = "D:/wasm-research/rust/backend"
command = "wasm-pack"
args = ["build", "--target", "nodejs", "--out-dir", "../wasm"]

[tasks.build]
dependencies = ["compile-singlethread", "compile-multithread", "compile-backend"]